# config.yaml

train_params:
  custom_dataset: False
  dataset: 'jakartaresearch/google-play-review'
  teacher_model: firqaaa/indo-sentence-bert-base # model from huggingface
  student_model: sentence-transformers/paraphrase-MiniLM-L3-v2

evaluation_params:
  evaluate: False